### ISSUE TITLE
precompiled version

### ISSUE THREAD

**Issue by ghost** [thefranke/dirtchamber#1]
in your readme file you said :

> "A precompiled version is available online"

but when clicking on that link only page  http://tobias-franke.eu/projects/dirtchamber/doc/ 
opens and there are no exe files.
please tell me where to download them.
thakn you!

**Comment by thefranke** [comment]
Hi @3DdeepAI, the readme refers to the precompiled doxygen documentation.

Github projects have a release page under which you can usually find binaries:
https://github.com/thefranke/dirtchamber/releases

**Comment by ghost** [comment]
thank you very much. I now  found it, but unfortunately I had to manually add zlib1.dll after the msi installation on my Win10 64bit. However now it works.
